#!/bin/bash
# generate-aero-colors.sh — Generate hyprtk-aero waybar + rofi from pywal colors
# Called by wallpaper-colors.sh, wal-watcher.sh, wallpaper-restore.sh

WAL_COLORS="$HOME/.cache/wal/colors"
WAYBAR_OUT="$HOME/.cache/wal/colors-waybar-aero.css"
ROFI_OUT="$HOME/hyprtk/configs/rofi/variants/hyprtk-aero.rasi"
ROFI_LIVE="$HOME/.config/rofi/variants/hyprtk-aero.rasi"

[ -f "$WAL_COLORS" ] || exit 1

# Read pywal colors (color0-color15)
i=0
while IFS= read -r line; do
    colors[$i]="$line"
    i=$((i + 1))
done < "$WAL_COLORS"

# foreground = color7, background = color0
fg="${colors[7]}"
bg="${colors[0]}"

# --- Waybar colors.css ---
cat > "$WAYBAR_OUT" <<EOF
/* Auto-generated by generate-aero-colors.sh — do not edit */
@define-color foreground ${fg};
@define-color background ${bg};

@define-color color0 ${colors[0]};
@define-color color1 ${colors[1]};
@define-color color2 ${colors[2]};
@define-color color3 ${colors[3]};
@define-color color4 ${colors[4]};
@define-color color5 ${colors[5]};
@define-color color6 ${colors[6]};
@define-color color7 ${colors[7]};
@define-color color8 ${colors[8]};
@define-color color9 ${colors[9]};
@define-color color10 ${colors[10]};
@define-color color11 ${colors[11]};
@define-color color12 ${colors[12]};
@define-color color13 ${colors[13]};
@define-color color14 ${colors[14]};
@define-color color15 ${colors[15]};

@define-color sky ${colors[6]};
@define-color green ${colors[2]};
@define-color sapphire ${colors[4]};
@define-color yellow ${colors[3]};
@define-color red ${colors[1]};
@define-color mauve ${colors[5]};
EOF

# Convert hex to rgb for rgba()
hex_to_rgb() {
    local hex="${1#\#}"
    printf "%d, %d, %d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

bg_rgb=$(hex_to_rgb "$bg")

# Generate rofi variant
cat > "$ROFI_OUT" <<EOF
/*  -----------------------------------------------------
    hyprtk-aero — Windows 7 Aero Glass (pywal auto-generated)
    -----------------------------------------------------  */
window {
    background-color:            rgba(${bg_rgb},0.70);
    border-color:                rgba(255,255,255,0.20);
}

inputbar {
    text-color:                  #ffffff;
    border-color:                rgba(255,255,255,0.15);
    background-color:            rgba(255,255,255,0.06);
}

textbox-prompt-colon {
    background-color:            ${colors[4]};
    text-color:                  #ffffff;
}

entry {
    text-color:                  #ffffff;
}

mode-switcher {
    text-color:                  #ffffff;
}

button {
    background-color:            rgba(255,255,255,0.05);
    text-color:                  #ffffff;
    border-color:                rgba(255,255,255,0.15);
}

button selected {
    background-color:            ${colors[4]};
    text-color:                  #ffffff;
    border-color:                rgba(255,255,255,0.30);
}

element {
    background-color:            rgba(255,255,255,0.05);
    border-color:                rgba(255,255,255,0.15);
}

element normal.normal,
element normal.urgent,
element normal.active {
    text-color:                  ${fg};
}

element selected.normal {
    background-color:            ${colors[5]};
    text-color:                  #ffffff;
    border-color:                rgba(255,255,255,0.30);
}

element selected.urgent,
element selected.active {
    text-color:                  ${fg};
}

element alternate.normal,
element alternate.urgent,
element alternate.active {
    text-color:                  ${fg};
}

message {
    background-color:            rgba(255,255,255,0.06);
    text-color:                  #ffffff;
    border-color:                rgba(255,255,255,0.15);
}

textbox {
    text-color:                  #ffffff;
}

error-message {
    background-color:            rgba(220,80,80,0.30);
    text-color:                  #ffffff;
    border-color:                rgba(255,100,100,0.30);
}
EOF

# Sync rofi to live if it exists and is a different path
if [ -f "$ROFI_OUT" ] && [ -d "$(dirname "$ROFI_LIVE")" ]; then
    rofi_out_resolved="$(readlink -f "$ROFI_OUT" 2>/dev/null || echo "$ROFI_OUT")"
    rofi_live_resolved="$(readlink -f "$ROFI_LIVE" 2>/dev/null || echo "$ROFI_LIVE")"
    if [ "$rofi_out_resolved" != "$rofi_live_resolved" ]; then
        cp "$ROFI_OUT" "$ROFI_LIVE"
    fi
fi
