-- ----------------------------------------------------- 
-- Autostart
-- ----------------------------------------------------- 

-- Apps

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--exec-once = sleep 5 && pamac-tray-plasma

-- Scripts

--exec-once = ~/hyprtk/scripts/octopi.sh

-- System

hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon &")
    hl.exec_cmd("dunst")
    hl.exec_cmd("hyprctl setcursor Adwaita 24")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("wal -R -q")
    hl.exec_cmd("bash -c \"sleep 3 && cd ~/.local/share/Matuwall && source .venv/bin/activate && LD_PRELOAD=/usr/lib/libgtk4-layer-shell.so matuwall\"")
    hl.exec_cmd("rm -f /tmp/wobpipe && mkfifo /tmp/wobpipe && tail -f /tmp/wobpipe | wob -c ~/.config/wob/wob.ini &")
    hl.exec_cmd("~/hyprtk/scripts/lockscreentime.sh")
    hl.exec_cmd("~/hyprtk/hypr/scripts/wallpaper-restore.sh")
    hl.exec_cmd("~/hyprtk/hypr/scripts/wal-watcher.sh &")
    hl.exec_cmd("~/hyprtk/gtk/gtk.sh")
    hl.exec_cmd("cat ~/.cache/wal/colors.Xresources > ~/.Xresources")
    hl.exec_cmd("~/hyprtk/scripts/reset-sudo-attempts.sh")
    hl.exec_cmd("~/hyprtk/scripts/bash-cleanup.sh")
    hl.exec_cmd("~/hyprtk/scripts/set-timezone.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("xhost +local:")
    hl.exec_cmd("hyprctl dismissnotify")
end)

