-- ----------------------------------------------------- 
-- Environment Variables
-- ----------------------------------------------------- 

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("WLR_NO_HARDWARE_CURSORS", "1")
hl.env("WLR_RENDERER_ALLOW_SOFTWARE", "1")
hl.env("XCURSOR_SIZE", "24")
hl.env("GTK_THEME", "Kripton-v40:dark")
hl.env("XDG_SESSION_TYPE", "wayland")

