# ----------------------------------------------------- 
# Layouts
# ----------------------------------------------------- 

# HYprland update 0.55 - removes dwindle here, leaving in code in case of reversal
#dwindle {
#    pseudotile = true
#    preserve_split = true
#}

master {
    new_status = master
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
